import '../styles/global.css'
// import 'antd/dist/reset.css';

import { Metadata } from 'next'
import SideBar from '../components/sideabar'

import React, { Suspense } from 'react'
import { Layout } from 'antd'
import { Header, Content, Footer } from 'antd/lib/layout/layout'
import { AntdRegistry } from '@ant-design/nextjs-registry'

export const metadata: Metadata = {
  title: {
    template: '%s',
    default: 'home',
  },
  description: 'Generated by Next.js',
}
export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  
  const colorBgContainer = '#fff'
  const borderRadiusLG = '0.8'


  return (
    <html lang="en">
      <head>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1122134236443449"
      crossOrigin="anonymous"></script>
      </head>
      <body>
        <AntdRegistry>
          <div id="container">
            <Layout className="ant-layout-has-sider">
              <SideBar  />
              <Layout>
                <Header className='hidden lg:block' style={{ padding: 0, background: colorBgContainer }} />
                <Content style={{ /* margin: '24px 16px 0' */ }}>
                  <div className='p-0 lg:p-[24px]'
                    style={{
                      minHeight: 360,
                      background: colorBgContainer,
                      borderRadius: borderRadiusLG,
                    }}
                  >
                    {children}
                  </div>
                </Content>
                <Footer style={{ textAlign: 'center' }}>
                  Is Just Blog ©{new Date().getFullYear()} Created by LHJ
                </Footer>
              </Layout>
            </Layout>
          </div>
        </AntdRegistry>
      </body>
    </html>
  )
}
